name: '📝 Get Next Version'
description: 'Get next semantic version'

inputs:
  github_token:
    description: 'Github token'
    required: true
  extra_plugins:
    required: false
    description: 'Extra plugins for pre-install. You can also specify specifying version range for the extra plugins if you prefer.'

outputs:
  last_release_version:
    description: 'Version of the last release'
    value: ${{ steps.semantic.outputs.last_release_version }}
  new_release_version:
    description: 'Version of the new release'
    value: ${{ steps.semantic.outputs.new_release_version }}
  new_release_git_tag:
    description: 'Github tag of the new release'
    value: ${{ steps.semantic.outputs.new_release_git_tag }}
  new_release_published:
    description: 'Whether a new release was published'
    value: ${{ steps.semantic.outputs.new_release_published }}

runs:
  using: composite
  steps:
    - name: ⏭️ Determine the next release version
      id: semantic
      uses: cycjimmy/semantic-release-action@v4
      with:
        dry_run: true
        semantic_version: 24.2.3
        extra_plugins: ${{ inputs.extra_plugins }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
