name: "🚀 Deploy ECS service"
description: "Deploy service on ECS with terraform"

inputs:
  AWS_REGION:
    description: "The AWS region to use"
    required: true
    default: eu-west-1
  AWS_ECR_DEPLOYMENT_ROLE:
    description: "The ARN of the AWS github-ci role the role to use for ECR deployment"
    required: false
  TERRAFORM_VERSION:
    description: "The version of Terraform to use"
    required: false
    default: 1.9.8

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-Terraform@v3
      with:
        terraform_version: ${{ inputs.TERRAFORM_VERSION }}

    - name: Terraform version
      shell: bash
      run: terraform --version

    - name: "Configure Shared Account AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.AWS_ECR_DEPLOYMENT_ROLE }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: Terraform apply
      shell: bash
      run: |
        cd terraform/shared
        terraform init
        terraform apply -auto-approve
