name: '🏗️ Build and push image'
description: 'Build and push image to ECR'

inputs:
  AWS_REGION:
    description: 'The AWS region to use'
    required: true
  AWS_ROLE_ARN:
    description: 'The ARN of the AWS github-ci role to use to push to ECR'
    required: true
  ECR_REPOSITORY:
    description: 'The name of the ECR repository'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 🔐 Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.AWS_ROLE_ARN }}
        role-session-name: GitHub-Action-Role
        aws-region: ${{ inputs.AWS_REGION }}

    - name: 🔓 Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: 🐳 Docker Metadata
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: '${{ steps.login-ecr.outputs.registry }}/${{ inputs.ECR_REPOSITORY }}'
        tags: |
          latest
          type=sha,prefix=sha-,format=long
          type=ref,event=branch
          type=ref,event=pr
          type=ref,event=tag

    - name: 🏗️ Build and push
      if: steps.check-image-tag.outputs.exists != 'true'
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
